workflows:
  android-build:
    name: Compilar APK Android
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Criar arquivos nativos do Android
        script: |
          flutter create --platforms=android .
      - name: Obter dependencias do Flutter
        script: |
          flutter packages pub get
      - name: Compilar APK
        script: |
          flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - wldecant@gmail.com
